### ISSUE TITLE
Streaming result text?

### ISSUE THREAD

**Issue by judgej** [Dhii/shell-interop#1]
Your command result text is a string, which will have limitations if the result contains a large amount of data. If the result is a streaming object, then running out of memory can be avoided.

**Comment by XedinUnknown** [comment]
@judgej, thank you for your suggestion. You are absolutely right. I already plan to overcome this limitation via a callback in the implementation ([here](https://github.com/Dhii/shell), in progress right now). If callback is supplied, it will receive the output every time there is any, and no output will be returned via `getStandardOutput()` or `getErrorOutput()`. This will be reflected in the specs.

**Comment by XedinUnknown** [comment]
More specifically, you will be able to supply a callback for each of the output pipe "ids". The callback should be supplied to the instance of `CommandInterface`, I believe.

**Comment by XedinUnknown** [comment]
Closed as this is more a question of implementation, which is taking place in the [`dhii/shell`](https://github.com/Dhii/shell) project.
